### PR TITLE
replace beberlei/assert with webmozart/assert

### LINKED ISSUE #516: "beberlei/assert" requires the extension "intl"
## Bug report

| Question    | Answer
| ------------| ---------------
| Box version | 3.11.0 
| PHP version | 8.0.0 
| Platform with version | php:8-cli-alpine (docker)
| Github Repo | - 

```bash
Step 8/19 : RUN php box.phar compile
 ---> Running in 5d5b954bc039

Box Requirements Checker
========================

> Using PHP 8.0.0
> PHP is using the following php.ini file:
  WARNING: No configuration file (php.ini) used by PHP!

> Checking Box requirements:
  ...E....


 [ERROR] Your system is not ready to run the application.


Fix the following mandatory requirements:
=========================================

 * The package "beberlei/assert" requires the extension "intl". Enable it or
   install a polyfill.

```

I think we need to add https://github.com/symfony/polyfill-intl-icu as a box requirement.

### PR DESCRIPTION
**Pull request by smoench**
resolves #516

### CODE REVIEW

**Comment by theofidry** [comment]
👌

**Comment by theofidry** [comment]
Thanks a lot! That's something I've longed wished for so very happy to see it happening 😄

File: src/Box.php [hunk 1]
```diff
@@ -350,19 +350,19 @@ public function sign(string $key, ?string $password): void
     {
         $pubKey = $this->file.'.pubkey';
 
-        Assertion::writeable(dirname($pubKey));
-        Assertion::extensionLoaded('openssl');
+        Assert::writable(dirname($pubKey));
+        Assert::true(extension_loaded('openssl'));
```
Comment (villfa) [inline src/Box.php:354]: I think we should specify a message here to help users understand why there is an error
