### PR TITLE
Requirements checker now logs to stderr

### LINKED ISSUE #678: Requirements Checker outputs on stdout instead of stderr
## Bug report

| Question    | Answer
| ------------| ---------------
| Box version | 3.16.0
| PHP version | 8.1.7
| Platform with version | Linux

This could also be considered a CR/FR but as it causes unexpected behaviour for software packaged with box, I rather think of it as a bug. The program arises when the program being packaged with box writes structured output (e.g. json) to stdout and its corresponding (debug-)logs to stderr. Activating debug-level logging via `-vvv` for the packaged program now breaks the json-output as the box-logs are also printed on stdout.
As the output of the requirements checker is rather *diagnostic* then *conversational* (see: https://pubs.opengroup.org/onlinepubs/9699919799/functions/stderr.html), I would expect to have that output on stderr.

For discussions around using stdout/stderr for logging:
- https://unix.stackexchange.com/questions/331611/do-progress-reports-logging-information-belong-on-stderr-or-stdout
- https://stackoverflow.com/questions/4919093/should-i-log-messages-to-stderr-or-stdout

IMO this should be resolved by just switching the stream [here](https://github.com/box-project/box/blob/master/requirement-checker/src/Printer.php#L151) but in case this is considered a BC, it should at least become configurable somehow.

### PR DESCRIPTION
**Pull request by arnegroskurth**
Fixes #678

### CODE REVIEW

File: requirement-checker/src/Printer.php [hunk 1]
```diff
@@ -148,6 +148,14 @@ public function printv(string $message, int $verbosity, ?string $style = null):
             $this->supportColors ? $this->styles['reset'] : ''
         );
 
-        echo $message;
+        if (getenv('BOX_REQUIREMENTS_CHECKER_LOG_TO_STDOUT') === '1')
+        {
+            // use echo/print to support output buffering
+            print $message;
```
Comment (theofidry) [inline requirement-checker/src/Printer.php:154]: why `print` vs `echo`?

File: requirement-checker/src/Printer.php [hunk 2]
```diff
@@ -148,6 +148,14 @@ public function printv(string $message, int $verbosity, ?string $style = null):
             $this->supportColors ? $this->styles['reset'] : ''
         );
 
-        echo $message;
+        if (getenv('BOX_REQUIREMENTS_CHECKER_LOG_TO_STDOUT') === '1')
+        {
```
Comment (theofidry) [inline requirement-checker/src/Printer.php:152]: let's keep to the traditional CS of the project:

```php
if (smth) {
    // ...
} else {
    // ...
}
```

Sorry I don't remember if `make cs` fixes this or not (I don't think it is applied to the requirement checker at all)

File: doc/requirement-checker.md [hunk 3]
```diff
@@ -135,6 +135,16 @@ $ BOX_REQUIREMENT_CHECKER=0 php box.phar
 ```
 
 
+## Logging to stdout
+
+Since version x.x.x, box logs the requirements checker output to `stderr` per default (see: [#678](https://github.com/box-project/box/issues/678)).
```
Comment (theofidry) [inline doc/requirement-checker.md:140]:
```suggestion
Since version 3.17.0, box logs the requirements checker output to `stderr` per default (see: [#678](https://github.com/box-project/box/issues/678)).
```

File: UPGRADE.md [hunk 4]
```diff
@@ -1,3 +1,9 @@
+
+# From 3.16.0 to x.x.x
```
Comment (theofidry) [inline UPGRADE.md:2]:
```suggestion
# From 3.17.0 to x.x.x
```

**Review by theofidry — APPROVED** [review]
Thanks for the PR!

A few nitpicks but looks good to me! Since there is so much changes for the next release I'd more confident to tag a new minor version.

File: UPGRADE.md (hunk 4 above)
Comment (arnegroskurth) [reply UPGRADE.md]: If you plan to release this with 3.17.0, this has to be `# From 3.16.0 to 3.17.0`, right?

File: requirement-checker/src/Printer.php (hunk 1 above)
Comment (arnegroskurth) [reply requirement-checker/src/Printer.php]: Just a habit - will not make any difference but updated it to the previous style.

File: requirement-checker/tests/bootstrap.php [hunk 5]
```diff
@@ -0,0 +1,6 @@
+<?php
+
+require_once __DIR__ . '/../vendor/autoload.php';
+
+// required for output buffering
+putenv('BOX_REQUIREMENTS_CHECKER_LOG_TO_STDOUT=1');
```
[the remark this answers is not in the document]
Comment (arnegroskurth) [reply requirement-checker/tests/bootstrap.php]: Moved it.

File: requirement-checker/src/Printer.php (hunk 2 above)
Comment (arnegroskurth) [reply requirement-checker/src/Printer.php]: CS is updated.

File: UPGRADE.md (hunk 4 above)
Comment (theofidry) [reply UPGRADE.md]: Correct, my bad

**Comment by theofidry** [comment]
🤔 not sure why the End-to-End Tests / e2e-Tests: e2e_check_requirements build is failing. The build is passing on master so it should be related, but `tee` should pick up the stderr

**Comment by arnegroskurth** [comment]
> thinking not sure why the End-to-End Tests / e2e-Tests: e2e_check_requirements build is failing. The build is passing on master so it should be related, but `tee` should pick up the stderr

I'm not really able to interpret the output but the latter failing test-case seems to complain about failed writes due to potentially full disk: https://github.com/box-project/box/runs/7039442617?check_suite_focus=true#step:6:2056

And I don't think that `tee`forwards stderr (Try: `sh -c "echo foo > /dev/stderr" | tee file.ext`) - where is that used? Just setting `BOX_REQUIREMENTS_CHECKER_LOG_TO_STDOUT=1` for all tests might be the easiest way out here.

**Comment by theofidry** [comment]
>I'm not really able to interpret the output but the latter failing test-case seems to complain about failed writes due to potentially full disk

Yes you can ignore this one I need to check how to fix it.

>where is that used? 

In the `Makefile`. You should be able to run the tests with `make e2e_check_requirements`

File: UPGRADE.md [hunk 6]
```diff
@@ -1,3 +1,9 @@
+
+# From 3.16.0 to 3.17.0
```
Comment (theofidry) [inline UPGRADE.md:2]:
```suggestion
# From 4.0 to 4.1.0
```

**Comment by theofidry** [comment]
Thank a lot @arnegroskurth
